# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y7essZHx7ysZaRDPtlC2_VTWurTUibE-
"""

import json
import requests
import pandas as pd
from pandas.io.json import json_normalize

url = 'https://pokeapi.co/api/v2/pokemon'

#Saqué la api de esta página "https://pokeapi.co/"

response = requests.get(url)
results = response.json()
results

data = pd.DataFrame(results)
data

flattened_data = json_normalize(results['results'])
flattened_data

url = 'https://pokeapi.co/api/v2/pokemon/{}'

results = []

for i in range(3):
    response = requests.get(url.format(1))
    results.append(response.json())
    #result

pokemons = pd.DataFrame(results)
pokemons

pokemons.shape

pokemons_flat = json_normalize(results)
pokemons_flat

pokemons_flat.shape

