# -*- coding: utf-8 -*-
"""FeedsLab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qsulvjmFFZUT2NBC4vTJBHtpohFWZJ0m
"""

pip install feedparser

import feedparser

url = 'http://feeds.feedburner.com/oreilly/radar/atom'

feeds = feedparser.parse(url)
feeds

feeds.keys()

feeds.feed.keys()

print (feeds.feed.title)
print (feeds.feed.subtitle)
print (feeds.feed.link)

len(feeds.entries)

list(feeds.entries[0].keys())

titles = [entry.title for entry in feeds.entries]
titles

counter = 0
for title in titles:
    if 'Four short links' in title:
        counter += 1
        
counter*100/len(titles)

import pandas as pd

df = pd.DataFrame(feeds.entries)
df

df['chars'] = df['title'].apply(len)
df[['title', 'author', 'title', 'chars']].sort_values('chars', ascending=False)

df[df['summary'].apply(lambda x: 'machine learning' in x)]['title']

