CREATE DATABASE lab_mysql;
USE lab_mysql;


CREATE TABLE IF NOT EXISTS cars(
CarPk INT NOT NULL AUTO_INCREMENT=0 PRIMARY KEY,
vin VARCHAR(55) NOT NULL,
manufacturer VARCHAR(80) NOT NULL,
model VARCHAR(55) NOT NULL,
year VARCHAR(15) NOT NULL,
color VARCHAR(55)
);

CREATE TABLE IF NOT EXISTS sales_person(
StaffPk INT NOT NULL AUTO_INCREMENT=0 PRIMARY KEY,
StaffId VARCHAR(28) NOT NULL,
name VARCHAR(125) NOT NULL,
storeAtCompany VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS customer(
CustomPk INT NOT NULL AUTO_INCREMENT=0 PRIMARY KEY,
customer_id VARCHAR(25) NOT NULL,
name VARCHAR(120) NOT NULL,
telephone VARCHAR(18) NOT NULL,
email VARCHAR(255),
address VARCHAR(150) NOT NULL,
city VARCHAR(35) NOT NULL,
state VARCHAR(255) NOT NULL,
country VARCHAR(80) NOT NULL,
zip_code VARCHAR(11) NOT NULL
);

CREATE TABLE IF NOT EXISTS invoice_number(
invoicePk INT NOT NULL AUTO_INCREMENT=0 PRIMARY KEY,
invoice_number VARCHAR NOT NULL,
date_invoice DATETIME NOT NULL,
CarPK INT NOT NULL,
CustomPk INT NOT NULL,
StaffPk INT NOT NULL,  
FOREIGN KEY(CarPk) REFERENCES cars(CarPk), 
FOREIGN KEY(StaffPk) REFERENCES sales_person(StaffPk),
FOREIGN KEY (CustomPk) REFERENCES customer(CustomPk)
);
