# -*- coding: utf-8 -*-
"""Juego_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12nUBFSySIBAeqP4CPe4maumlKcSXIKCH
"""

import random

elegir_random = random.randrange(0, 3)
 
def empezar():

  print("Hola, soy Saul 🧔🏽")
  print("Bienvenido al juego de piedra 💎, papel 📄 o tijera ✂️")
  print("Si elijes piedra, pon 1, si eliges papel pon 2 o si te decides por tijera aprieta el 3")
  eleccion = int(input("Que elijes: "))

  if eleccion == 1:
    jugador="Piedra 💎"
  if eleccion == 2:
     jugador="Papel 📄"
  if eleccion == 3:
     jugador="Tijera ✂️"
  print("Elegiste",jugador)


  if elegir_random == 0:
     saul="Piedra 💎"
  if elegir_random == 1:
     saul="Papel 📄"
  if elegir_random == 2:
     saul="Tijera ✂️"
  else:
    print("No pusiste bien el número")
  print("Yo elijo",saul)


  if saul == "Piedra 💎" and jugador == "Papel 📄":
    print("El papel envuelve a la piedra, me ganaste 😡")
  elif saul == "Papel 📄" and jugador == "Tijera ✂️":
    print("Las tijeras cortan al papel, me ganaste 😡")
  elif saul == "Tijera ✂️" and jugador == "Piedra 💎":
    print("Una piedra rompe las tijeras, me ganaste 😡")

  if saul == "Papel 📄" and jugador == "Piedra 💎":
    print("El papel envuelve a la piedra, Gané!! 👊🏾")
  elif saul == "Tijera ✂️" and jugador == "Papel 📄":
    print("Las tijeras cortan al papel, Gané!! 👊🏾")
  elif saul == "Piedra 💎" and jugador == "Tijera ✂️":
    print("Una piedra rompe las tijeras, Gané!! 👊🏾")
  elif saul == jugador:
    print("NADIE GANÓ 🤷🏽‍♂️")


  print("Quieres volver a jugar? 🤷🏽‍♂️")
  si = int(input("Si quieres jugar PRESIONA 0 sino, preciona cualquier teclaotro número"))
  if si == 0:
    empezar()
  else: 
     print("FIN")

empezar()