# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pOir0eb4GWRCKi4WB27WPywUs-LdSvfv
"""

import pandas as pd

pip install PyMySQL

import pymysql
import sqlalchemy

engine=('mysql+pymysql://guest:relational@relational.fit.cvut.cz')

users=pd.read_sql_query('SELECT * FROM stats.users', engine)
users.head()

users=users.rename(columns = {'Id':'userId'})
users.head()

posts=pd.read_sql_query('SELECT * FROM stats.posts', engine)
posts.head()

posts=posts.rename(columns = {'Id':'postId','OwnerUserId':'userId'})
posts.head()

new_users=pd.DataFrame(zip(users.userId, users.Reputation, users.Views,users.UpVotes,users.DownVotes))
new_users=new_users.rename(columns = {0:'userId',1:'Reputation',2:'Views',3:'UpVotes',4:'DownVotes'})
new_users.head()

new_posts=pd.DataFrame(zip(posts.postId,posts.Score,posts.userId,posts.ViewCount,posts.CommentCount))
new_posts=new_posts.rename(columns = {0:'postId',1:'Score',2:'userId',3:'ViewCount',4:'CommentCount'})
new_posts.head()

merge_df = new_users.merge(new_posts, on='userId')
merge_df.head()

new_users2=pd.DataFrame(zip(users.userId, users.Reputation, users.Views,users.UpVotes,users.DownVotes))
new_users2=new_users.rename(columns = {0:'userId',1:'Reputation',2:'Views',3:'UpVotes',4:'DownVotes'})
new_users2.head()

new_users2['userId'].replace(-1,1, inplace=True)

new_users2.head()

new_posts=pd.DataFrame(zip(posts.postId,posts.Score,posts.userId,posts.ViewCount,posts.CommentCount))
new_posts=new_posts.rename(columns = {0:'userId',1:'Score',2:'UserpostId',3:'ViewCount',4:'CommentCount'})
new_posts.head()

merge_df = new_users2.merge(new_posts, on='userId')
merge_df.head()

merge_df.max()

merge_df.min()

