# -*- coding: utf-8 -*-
"""MarketingPara.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ojGCdFxpcQ8McW250kLmUlSEd4EojQ2J
"""

import requests

url = 'https://es.wikipedia.org/wiki/Mercadotecnia'

html = requests.get(url).content

from bs4 import BeautifulSoup

soup = BeautifulSoup(html, 'html.parser')

links = soup.find_all('a')

links_2 = [i.get('href') for i in links]

links_3 = list(set([str(i) for i in links_2]))
print(links_3)

domain = 'http://wikipedia.org'

absolute = [i for i in links_3 if 'http' in i]
absolute_1 = [i for i in absolute if '%' not in i]
relative = [i for i in links_3 if i not in absolute]
relative_2 = [domain+i for i in relative]
relative_3 = [i for i in relative_2 if '%' not in i]
combine = list(set(absolute_1+relative_3))
combine_2 = [i.replace('http', 'https').replace('httpss','https') for i in combine]
combine_2

import os

os.mkdir(r'C:\Users\aquir\IronHack\datamex0120\module-1\lab-parallelization\your-code\wikipedia')
os.chdir(r'C:\Users\aquir\IronHack\datamex0120\module-1\lab-parallelization\your-code\wikipedia')

from slugify import slugify

def index_page(link):  
    try:
        html=requests.get(link).content
        slug=slugify(html)
        file=open('slugified','w')
        file=file.write(slug)
    except:
        pass