# -*- coding: utf-8 -*-
"""LabImportExport.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-6lvC9f_JX9L1kjeCmLA9pfQx1qyvTVj
"""

import numpy as np
import pandas as pd
from urllib.request import urlopen
import json

response = urlopen("https://data.nasa.gov/resource/y77d-th95.json")
json_data = response.read().decode('utf-8', 'replace')

nasa = pd.read_json(json_data, orient='records')
nasa.head()

nasa['fall'].value_counts()

nasa.to_json('nasa.json', orient='records')

"""Challenge2"""

cols = ['time', 'rad_flow', 'fpv_close', 'fpv_open', 'high', 'bypass', 'bpv_close', 'bpv_open', 'class']
tst_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/statlog/shuttle/shuttle.tst'

shuttle = pd.read_csv(tst_url, sep=' ', names = cols)

shuttle.head()

shuttle.to_csv('shuttle.csv', sep=',', index=False)

"""Chanllenge 3"""

!pip install -q xlrd

astronaut = pd.read_excel('astronauts.xls')

astronaut.head()

astronaut['Undergraduate Major'].value_counts().head()

astronaut.to_csv('astronaut.csv', sep='\t', index=False)